export const translations: Record<string, Record<string, string>> = {
    ar: {
        title: "فرقة المزيود | الموقع الرسمي",
        nav_main: "الرئيسية", nav_songs: "الأغاني", nav_events: "الفعاليات", nav_tools: "أدوات", lang_switcher: "EN", home_title: "فرقة المزيود", home_subtitle: "الموقع الرسمي", songs_title: "الأعمال الفنية", songs_subtitle: "استمع لأحدث الأغاني والفيديوهات", music_spotify: "سبوتيفاي", music_youtube: "يوتيوب", events_title: "الفعاليات القادمة", events_loading: "جاري تحميل الفعاليات...", events_none: "لا توجد فعاليات قادمة حالياً.", tools_title: "أدوات إعلامية", tool_card_title: "كڤر فرقة المزيود", tool_card_desc: "إنشاء صور احترافية للكفرات",
        event_announcer_title: "إعلانات الفعاليات", event_announcer_desc: "تصميم إعلانات للفعاليات القادمة", event_announcer_step1: "الخطوة 1: اختر الفعالية", event_announcer_step2: "الخطوة 2 (اختياري): تعديل الترحيب", event_announcer_welcome_placeholder: "يا مرحبابكم", event_announcer_step3: "الخطوة 3: ارفع صورة الخلفية", event_announcer_choose_image: "اختر صورة", event_announcer_download: "تحميل الإعلان", back_button: "العودة للأدوات",
        event_now: "الفعالية قائمة الآن", event_starts_in_days: "يبدأ خلال {days} أيام", event_starts_in_hours: "يبدأ خلال {hours} ساعات",
        tool_step1: "الخطوة 1: اختر المقاس", tool_square: "مربع", tool_story: "ستوري", tool_step2: "الخطوة 2: ارفع صورتك", tool_choose_image: "اختر صورة", tool_step3: "الخطوة 3 (اختياري): أضف نصاً", tool_placeholder: "اكتب كلمتين بحد أقصى", tool_download: "تحميل الصورة", tool_loading: "جاري التحميل...",
        settings_title: "الإعدادات", settings_tools: "أدوات إعلامية", settings_language: "تغيير اللغة",
        settings_signin: "دخول الأعضاء",
        settings_signout: "تسجيل الخروج",
        passcode_prompt: "الرجاء إدخال رمز الدخول",
        passcode_title: "إدخال رمز الدخول",
        passcode_placeholder: "الرمز",
        passcode_enter_button: "دخول",
        error_wrong_passcode: "رمز الدخول غير صحيح.",
        countdown_days: "أيام",
        countdown_hours: "ساعات",
        countdown_minutes: "دقائق",
        countdown_seconds: "ثواني",
        add_event_button: "إضافة فعالية",
        add_event_title: "إضافة فعالية جديدة",
        edit_event_title: "تعديل الفعالية",
        event_name_label: "اسم الفعالية",
        event_date_label: "التاريخ",
        event_time_label: "الوقت",
        event_location_label: "الموقع",
        event_location_link_label: "رابط الموقع (اختياري)",
        event_name_placeholder: "مثال: حفل اليوم الوطني",
        event_location_placeholder: "مثال: دبي، الشارقة",
        event_location_link_placeholder: "https://maps.app.goo.gl/...",
        save_event_button: "حفظ الفعالية",
        form_error_all_fields: "الرجاء تعبئة جميع الحقول الإجبارية.",
        form_error_invalid_link: "الرجاء إدخال رابط صحيح.",
        edit_event_button: "تعديل",
        delete_event_button: "حذف",
        delete_confirm_message: "هل أنت متأكد أنك تريد حذف هذه الفعالية؟",
        // FIX: Add missing translations for LinksPage
        links_title: "روابطنا",
        links_spotify: "سبوتيفاي",
        links_youtube: "يوتيوب",
        links_instagram: "انستقرام",
        links_tiktok: "تيك توك",
    },
    en: {
        title: "Al Mazyooud Band | Official Website",
        nav_main: "Home", nav_songs: "Music", nav_events: "Events", nav_tools: "Tools", lang_switcher: "ع", home_title: "Al Mazyooud Band", home_subtitle: "Official Website", songs_title: "Artworks", songs_subtitle: "Listen to the latest songs and videos", music_spotify: "Spotify", music_youtube: "YouTube", events_title: "Upcoming Events", events_loading: "Loading events...", events_none: "No upcoming events at the moment.", tools_title: "Media Tools", tool_card_title: "Band Cover Maker", tool_card_desc: "Create professional cover photos",
        event_announcer_title: "Event Announcements", event_announcer_desc: "Design announcements for upcoming events", event_announcer_step1: "Step 1: Select Event", event_announcer_step2: "Step 2 (Optional): Edit Welcome", event_announcer_welcome_placeholder: "Welcome", event_announcer_step3: "Step 3: Upload Background Image", event_announcer_choose_image: "Choose Image", event_announcer_download: "Download Announcement", back_button: "Back to Tools",
        event_now: "Event is Live Now", event_starts_in_days: "Starts in {days} days", event_starts_in_hours: "Starts in {hours} hours",
        tool_step1: "Step 1: Choose Size", tool_square: "Square", tool_story: "Story", tool_step2: "Step 2: Upload Your Photo", tool_choose_image: "Choose Image", tool_step3: "Step 3 (Optional): Add Text", tool_placeholder: "Max two words", tool_download: "Download Image", tool_loading: "Loading...",
        settings_title: "Settings", settings_tools: "Media Tools", settings_language: "Change Language",
        settings_signin: "Member Login",
        settings_signout: "Sign Out",
        passcode_prompt: "Please enter the passcode",
        passcode_title: "Enter Passcode",
        passcode_placeholder: "Passcode",
        passcode_enter_button: "Enter",
        error_wrong_passcode: "Incorrect passcode.",
        countdown_days: "Days",
        countdown_hours: "Hours",
        countdown_minutes: "Minutes",
        countdown_seconds: "Seconds",
        add_event_button: "Add Event",
        add_event_title: "Add New Event",
        edit_event_title: "Edit Event",
        event_name_label: "Event Name",
        event_date_label: "Date",
        event_time_label: "Time",
        event_location_label: "Location",
        event_location_link_label: "Location Link (Optional)",
        event_name_placeholder: "e.g., National Day Concert",
        event_location_placeholder: "e.g., Dubai, Sharjah",
        event_location_link_placeholder: "e.g., https://maps.app.goo.gl/...",
        save_event_button: "Save Event",
        form_error_all_fields: "Please fill in all required fields.",
        form_error_invalid_link: "Please enter a valid URL.",
        edit_event_button: "Edit",
        delete_event_button: "Delete",
        delete_confirm_message: "Are you sure you want to delete this event?",
        // FIX: Add missing translations for LinksPage
        links_title: "Our Links",
        links_spotify: "Spotify",
        links_youtube: "YouTube",
        links_instagram: "Instagram",
        links_tiktok: "TikTok",
    }
};

export const IMAGE_MAKER_THEME_URL = "https://i.ibb.co/mrr52k05/IMG-1083.png";
export const EVENT_ANNOUNCER_LOGO_URL = 'https://i.ibb.co/21ZYL0mH/IMG-1630.png';
export const CIRCULAR_LOGO_WATERMARK_URL = 'https://i.ibb.co/ch9FdbXP/IMG-1086.png';
// FIX: Export missing URL constants for LinksPage
export const SPOTIFY_URL = "https://open.spotify.com/artist/3nSx2hjwIan6aGRyNSCOeF";
export const YOUTUBE_URL = "https://www.youtube.com/channel/UCJp0f-5yLq-l-H4J_g-l40g";
export const INSTAGRAM_URL = "https://www.instagram.com/almazyood";
export const TIKTOK_URL = "https://www.tiktok.com/@almazyood";
